// Generated by ToffeeScript 1.6.3-2
(function() {
  var http, request;

  request = require('request');

  http = require('http');

  function req(type, entity, data, cb) {
    var body, e, opts, res,
      _this = this;
    opts = {
      url: "http://" + account + ".oic.io/1/" + entity,
      headers: {
        "X-OIC-API-Key": apikey
      },
      json: data
    };
    request(opts, function() {
      e = arguments[0], res = arguments[1], body = arguments[2];
      return new cb(e, body);
    });
  };

  function run(server, domain, image, params, cb) {
    var data, e, extra, k, name, res, v, val, _ref,
      _this = this;
    data = {
      server: server,
      domain: domain,
      image: image
    };
    extra = '';
    if (params.environvars != null) {
      _ref = params.environvars;
      for (name in _ref) {
        val = _ref[name];
        extra += "-e " + name + "=" + val;
      }
      delete params.environvars;
    }
    data.extraparams = extra;
    for (k in params) {
      v = params[k];
      data[k] = v;
    }
    req('POST', 'containers', data, function() {
      e = arguments[0], res = arguments[1];
      return cb(e, res);
    });
  };

  exports.run = run;

}).call(this);
